services:

  app:
    build: .
    container_name: expense-app

    ports:
      - "4555:4555"

    environment:
      PORT: 4555

      DB_HOST: mysql
      DB_NAME: expense_tracker
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_DIALECT: mysql
      DB_PORT: 3306

      REDIS_URL: redis://redis:6379

    depends_on:
      - mysql
      - redis

    restart: unless-stopped


  mysql:
    image: mysql:8.0
    container_name: expense-mysql

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_tracker

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: expense-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: unless-stopped


volumes:

  mysql_data:

  redis_data: